export enum ButtonTypes {
    PRIMARY = 'PRIMARY',
    SECONDARY = 'SECONDARY',
    TERTIARY = 'TERTIARY',
    DANGER = 'DANGER',
    SUCCESS = 'SUCCESS',
    WARNING = 'WARNING',
    NEUTRAL = 'NEUTRAL',
}
