export const technologies = [
    'Angular',
    'AWS',
    'Azure',
    'C#',
    'CI/CD',
    'CSS',
    'Django',
    'Docker',
    'Figma',
    'Express.js',
    'Firebase',
    'Git',
    'Go',
    'Google Cloud',
    'GraphQL',
    'HTML',
    'Java',
    'JavaScript',
    'jQuery',
    'Kubernetes',
    'MongoDB',
    'Nestjs',
    'Next.js',
    'Node.js',
    'PHP',
    'PostgreSQL',
    'Prisma',
    'Python',
    'React',
    'React Native',
    'Redis',
    'REST APIs',
    'Ruby',
    'SASS',
    'Spring Boot',
    'Tailwind CSS',
    'TypeScript',
    'Vue.js',
]

export const foundMethod = [
    'LinkedIn',
    'Instagram',
    'Telegram',
    'Your Connections',
    'Other',
]

export const experience = [
    '0-1 year',
    '1-3 years',
    '3-5 years',
    '5-7 years',
    '7-10 years',
    '10+ years',
]
